import type { Category, Challenge, ChallengeComment, Checkin, Participation } from './types';
import type { UserProfile } from '@/lib/types';

/** DUEL category taxonomy — mirrors supabase/migrations/20260920000000_duel_platform.sql */
export const SEED_CATEGORIES: Category[] = [
  { id: 'coding', name: 'Coding & Building', emoji: '💻', color: '#22d3ee', tagline: 'Ship something every day', sort: 1 },
  { id: 'fitness', name: 'Fitness & Movement', emoji: '🏋️', color: '#f97316', tagline: 'Stronger, faster, further', sort: 2 },
  { id: 'reading', name: 'Reading & Learning', emoji: '📚', color: '#a78bfa', tagline: 'Pages turn into perspective', sort: 3 },
  { id: 'detox', name: 'Digital Detox', emoji: '📵', color: '#f43f5e', tagline: 'Reclaim your attention', sort: 4 },
  { id: 'mindfulness', name: 'Mindfulness & Focus', emoji: '🧘', color: '#34d399', tagline: 'Train the muscle between your ears', sort: 5 },
  { id: 'nutrition', name: 'Nutrition & Sleep', emoji: '🥗', color: '#84cc16', tagline: 'Fuel and recovery done right', sort: 6 },
  { id: 'creativity', name: 'Creativity & Craft', emoji: '🎨', color: '#f472b6', tagline: 'Make things, badly then brilliantly', sort: 7 },
  { id: 'finance', name: 'Money & Discipline', emoji: '💰', color: '#facc15', tagline: 'Small daily wins, compounding', sort: 8 },
  { id: 'language', name: 'Languages', emoji: '🗣️', color: '#60a5fa', tagline: 'Ten words a day adds up', sort: 9 },
  { id: 'outdoors', name: 'Outdoors & Adventure', emoji: '⛰️', color: '#2dd4bf', tagline: 'Get outside, every single day', sort: 10 },
];

/** Community members (personas) who create and join challenges. */
export const SEED_PROFILES: UserProfile[] = [
  { id: 'u-aya', username: 'aya_builds', name: 'Aya Rahman', avatar: null, avatarHue: 190, cover: null, bio: 'Frontend engineer. 3 challenges completed, 0 excuses.', location: 'Dhaka', website: '', joined: '2025-11-02T09:00:00.000Z', verified: true, persona: true },
  { id: 'u-marcus', username: 'marcuslifts', name: 'Marcus Cole', avatar: null, avatarHue: 20, cover: null, bio: 'Strength coach. I program the challenges I wish existed.', location: 'Austin, TX', website: '', joined: '2025-10-14T09:00:00.000Z', verified: true, persona: true },
  { id: 'u-lina', username: 'lina.reads', name: 'Lina Petrova', avatar: null, avatarHue: 265, cover: null, bio: '41 books last year. Ask me for a rec, I dare you.', location: 'Sofia', website: '', joined: '2025-12-01T09:00:00.000Z', verified: false, persona: true },
  { id: 'u-kenji', username: 'kenji_offgrid', name: 'Kenji Sato', avatar: null, avatarHue: 350, cover: null, bio: 'Deleted every social app in 2025. Never looked back.', location: 'Kyoto', website: '', joined: '2026-01-08T09:00:00.000Z', verified: false, persona: true },
  { id: 'u-priya', username: 'priya_flow', name: 'Priya Nair', avatar: null, avatarHue: 150, cover: null, bio: 'Meditation teacher. 10 minutes counts. Show up.', location: 'Bengaluru', website: '', joined: '2025-09-20T09:00:00.000Z', verified: true, persona: true },
  { id: 'u-diego', username: 'diego_maps', name: 'Diego Fuentes', avatar: null, avatarHue: 170, cover: null, bio: 'Trail runner & cartographer. The map is never finished.', location: 'Bogotá', website: '', joined: '2026-02-11T09:00:00.000Z', verified: false, persona: true },
  { id: 'u-sara', username: 'sara_compounds', name: 'Sara Kim', avatar: null, avatarHue: 45, cover: null, bio: 'Personal finance nerd. Automate everything.', location: 'Seoul', website: '', joined: '2026-01-27T09:00:00.000Z', verified: false, persona: true },
  { id: 'u-tomas', username: 'tomas_draws', name: 'Tomás Silva', avatar: null, avatarHue: 320, cover: null, bio: 'Illustrator. One sketch a day keeps the rust away.', location: 'Lisbon', website: '', joined: '2025-11-19T09:00:00.000Z', verified: false, persona: true },
];

const now = Date.now();
const daysAgoIso = (d: number) => new Date(now - d * 86400_000).toISOString();

export const SEED_CHALLENGES: Challenge[] = [
  { id: 'c-coding-30', creatorId: 'u-aya', title: '30 Days Coding', description: 'Write code every day for 30 days. One commit, one snippet, one bug fixed — it all counts. The only rule is that the editor opens daily.', categoryId: 'coding', durationDays: 30, difficulty: 'medium', dailyTask: 'Commit code or solve one problem, then log what you built.', coverUrl: '/images/covers/coding.jpg', tags: ['programming', 'consistency', 'commits'], status: 'open', participantCount: 1284, likeCount: 642, commentCount: 0, saveCount: 311, shareCount: 88, viewCount: 9210, completionCount: 402, createdAt: daysAgoIso(64) },
  { id: 'c-fitness-21', creatorId: 'u-marcus', title: '21 Days Fitness', description: 'Three weeks of daily movement: strength, cardio or mobility. Sessions are 30–45 minutes and scale from beginner to athlete.', categoryId: 'fitness', durationDays: 21, difficulty: 'hard', dailyTask: 'Complete a 30+ minute training session and note the workout.', coverUrl: '/images/covers/fitness.jpg', tags: ['training', 'strength', 'cardio'], status: 'open', participantCount: 2140, likeCount: 1187, commentCount: 0, saveCount: 540, shareCount: 143, viewCount: 15400, completionCount: 806, createdAt: daysAgoIso(58) },
  { id: 'c-detox-7', creatorId: 'u-kenji', title: '7 Days No Social Media', description: 'A full week off Instagram, TikTok, X and Facebook. Messenger and calls are fine. Expect day 2 to be rough — that is the point.', categoryId: 'detox', durationDays: 7, difficulty: 'hard', dailyTask: 'Zero social media apps. Log the urge you resisted and what you did instead.', coverUrl: '/images/covers/detox.jpg', tags: ['attention', 'dopamine', 'reset'], status: 'open', participantCount: 3310, likeCount: 2015, commentCount: 0, saveCount: 980, shareCount: 402, viewCount: 22100, completionCount: 1893, createdAt: daysAgoIso(51) },
  { id: 'c-reading-30', creatorId: 'u-lina', title: '30 Days Reading', description: 'Twenty pages or twenty minutes a day, whichever comes first. Fiction, non-fiction, papers — reading is reading.', categoryId: 'reading', durationDays: 30, difficulty: 'easy', dailyTask: 'Read 20+ pages and write one sentence about them.', coverUrl: '/images/covers/reading.jpg', tags: ['books', 'focus', 'habits'], status: 'open', participantCount: 1755, likeCount: 903, commentCount: 0, saveCount: 465, shareCount: 97, viewCount: 11800, completionCount: 712, createdAt: daysAgoIso(47) },
  { id: 'c-mind-14', creatorId: 'u-priya', title: '14 Days Meditation', description: 'Ten quiet minutes every morning for two weeks. Guided or silent — the practice is sitting down on purpose.', categoryId: 'mindfulness', durationDays: 14, difficulty: 'easy', dailyTask: 'Meditate for 10 minutes and rate your focus 1–5.', coverUrl: '/images/covers/mindfulness.jpg', tags: ['meditation', 'calm', 'morning'], status: 'open', participantCount: 1420, likeCount: 811, commentCount: 0, saveCount: 377, shareCount: 76, viewCount: 8600, completionCount: 640, createdAt: daysAgoIso(44) },
  { id: 'c-leetcode-45', creatorId: 'u-aya', title: '45 Days LeetCode Grind', description: 'One algorithmic problem a day for 45 days. Easy on Mondays, medium midweek, hard on weekends. Interview season proof-of-work.', categoryId: 'coding', durationDays: 45, difficulty: 'hard', dailyTask: 'Solve and submit one problem; link or name it in your check-in.', coverUrl: null, tags: ['algorithms', 'interviews', 'dsa'], status: 'open', participantCount: 860, likeCount: 402, commentCount: 0, saveCount: 288, shareCount: 51, viewCount: 6100, completionCount: 187, createdAt: daysAgoIso(40) },
  { id: 'c-sleep-7', creatorId: 'u-priya', title: '7 Days 5AM Club', description: 'Up at 05:00 for seven straight days, phones stay out of the bedroom. The first hour of the day belongs to you.', categoryId: 'nutrition', durationDays: 7, difficulty: 'medium', dailyTask: 'Wake at 05:00 and log your wake time plus first-hour activity.', coverUrl: null, tags: ['sleep', 'discipline', 'morning'], status: 'open', participantCount: 1130, likeCount: 522, commentCount: 0, saveCount: 240, shareCount: 64, viewCount: 7400, completionCount: 431, createdAt: daysAgoIso(36) },
  { id: 'c-nosugar-30', creatorId: 'u-marcus', title: '30 Days No Added Sugar', description: 'Cut added sugar for a month. Whole fruit is in, sweetened drinks and desserts are out. Read labels like a detective.', categoryId: 'nutrition', durationDays: 30, difficulty: 'hard', dailyTask: 'Log meals and confirm zero added sugar today.', coverUrl: '/images/covers/nutrition.jpg', tags: ['nutrition', 'energy', 'reset'], status: 'open', participantCount: 990, likeCount: 468, commentCount: 0, saveCount: 301, shareCount: 58, viewCount: 6800, completionCount: 289, createdAt: daysAgoIso(33) },
  { id: 'c-journal-14', creatorId: 'u-lina', title: '14 Days Journaling', description: 'One page, longhand, every night. No structure required — brain dump, gratitude list, or a rerun of the day.', categoryId: 'mindfulness', durationDays: 14, difficulty: 'easy', dailyTask: 'Write one journal page and note the prompt or topic.', coverUrl: null, tags: ['writing', 'reflection', 'evening'], status: 'open', participantCount: 760, likeCount: 355, commentCount: 0, saveCount: 199, shareCount: 33, viewCount: 4300, completionCount: 341, createdAt: daysAgoIso(30) },
  { id: 'c-budget-21', creatorId: 'u-sara', title: '21 Days Budget Control', description: 'Track every single expense for three weeks and review one spending category daily. Awareness first, cuts second.', categoryId: 'finance', durationDays: 21, difficulty: 'medium', dailyTask: 'Log all expenses and review one budget category.', coverUrl: null, tags: ['money', 'tracking', 'discipline'], status: 'open', participantCount: 640, likeCount: 289, commentCount: 0, saveCount: 214, shareCount: 29, viewCount: 3900, completionCount: 233, createdAt: daysAgoIso(27) },
  { id: 'c-draw-30', creatorId: 'u-tomas', title: '30 Days Drawing', description: 'One sketch a day for 30 days. Ugly sketches welcome — volume is the strategy. Prompts posted in the comments.', categoryId: 'creativity', durationDays: 30, difficulty: 'medium', dailyTask: 'Finish one sketch and describe or attach it.', coverUrl: '/images/covers/creativity.jpg', tags: ['art', 'sketching', 'practice'], status: 'open', participantCount: 830, likeCount: 476, commentCount: 0, saveCount: 260, shareCount: 44, viewCount: 5200, completionCount: 251, createdAt: daysAgoIso(24) },
  { id: 'c-steps-7', creatorId: 'u-diego', title: '7 Days 10K Steps', description: 'Ten thousand steps a day for a week. Walks, hikes, pacing while on calls — the counter does not judge.', categoryId: 'fitness', durationDays: 7, difficulty: 'easy', dailyTask: 'Hit 10,000 steps and log the count.', coverUrl: null, tags: ['walking', 'cardio', 'simple'], status: 'open', participantCount: 1980, likeCount: 890, commentCount: 0, saveCount: 402, shareCount: 121, viewCount: 12600, completionCount: 1104, createdAt: daysAgoIso(21) },
  { id: 'c-water-30', creatorId: 'u-marcus', title: '30 Days Hydration', description: 'Three litres of water a day for a month. Bottle on the desk, glass on the nightstand — engineer your environment.', categoryId: 'nutrition', durationDays: 30, difficulty: 'easy', dailyTask: 'Drink 3L water and tick it off.', coverUrl: null, tags: ['hydration', 'energy', 'simple'], status: 'open', participantCount: 1510, likeCount: 610, commentCount: 0, saveCount: 333, shareCount: 71, viewCount: 8900, completionCount: 688, createdAt: daysAgoIso(18) },
  { id: 'c-ship-14', creatorId: 'u-aya', title: '14 Days Ship It', description: 'Build and deploy a side project in two weeks. Day 14 ends with a public URL and a write-up. Scope small, ship real.', categoryId: 'coding', durationDays: 14, difficulty: 'hard', dailyTask: 'Push project work forward and note today’s milestone.', coverUrl: null, tags: ['sideproject', 'deploy', 'build'], status: 'open', participantCount: 540, likeCount: 301, commentCount: 0, saveCount: 187, shareCount: 46, viewCount: 3600, completionCount: 122, createdAt: daysAgoIso(15) },
  { id: 'c-spanish-30', creatorId: 'u-diego', title: '30 Days Spanish', description: 'Twenty minutes of Spanish daily: vocabulary, listening, or talking to yourself in the shower. Consistency beats intensity.', categoryId: 'language', durationDays: 30, difficulty: 'medium', dailyTask: '20 minutes of study; log 10 new words or a lesson.', coverUrl: '/images/covers/learning.jpg', tags: ['spanish', 'vocabulary', 'daily'], status: 'open', participantCount: 910, likeCount: 405, commentCount: 0, saveCount: 251, shareCount: 39, viewCount: 5600, completionCount: 268, createdAt: daysAgoIso(12) },
  { id: 'c-outside-7', creatorId: 'u-diego', title: '7 Days Outside', description: 'Thirty minutes outdoors every day for a week, in any weather. Daylight is a supplement you can’t buy in a bottle.', categoryId: 'outdoors', durationDays: 7, difficulty: 'easy', dailyTask: 'Spend 30+ minutes outside and note where you went.', coverUrl: null, tags: ['nature', 'daylight', 'walks'], status: 'open', participantCount: 720, likeCount: 322, commentCount: 0, saveCount: 158, shareCount: 27, viewCount: 4100, completionCount: 388, createdAt: daysAgoIso(9) },
  { id: 'c-marathon-90', creatorId: 'u-marcus', title: '90 Days Marathon Base', description: 'A twelve-week base-building block: four runs a week with a progressive long run. Check-ins log mileage, not feelings.', categoryId: 'fitness', durationDays: 90, difficulty: 'hard', dailyTask: 'Complete the scheduled run and log distance + pace.', coverUrl: null, tags: ['running', 'endurance', 'plan'], status: 'open', participantCount: 410, likeCount: 214, commentCount: 0, saveCount: 176, shareCount: 22, viewCount: 2900, completionCount: 61, createdAt: daysAgoIso(6) },
  { id: 'c-deepwork-14', creatorId: 'u-kenji', title: '14 Days Deep Work', description: 'One 90-minute distraction-free block daily: phone in another room, one tab, one task. Measure depth, not hours.', categoryId: 'mindfulness', durationDays: 14, difficulty: 'medium', dailyTask: 'Finish a 90-minute zero-interruption block and name the task.', coverUrl: null, tags: ['focus', 'productivity', 'monkmode'], status: 'open', participantCount: 1265, likeCount: 704, commentCount: 0, saveCount: 388, shareCount: 95, viewCount: 8100, completionCount: 497, createdAt: daysAgoIso(3) },
];

/** A few seeded comments so challenge pages feel alive on first load. */
export const SEED_COMMENTS: ChallengeComment[] = [
  { id: 'cm-1', challengeId: 'c-coding-30', userId: 'u-marcus', text: 'Day 12 done. The daily commit rule is brutal in the best way.', createdAt: daysAgoIso(4) },
  { id: 'cm-2', challengeId: 'c-coding-30', userId: 'u-lina', text: 'Joined yesterday — pairing this with the reading challenge keeps evenings screen-light.', createdAt: daysAgoIso(2) },
  { id: 'cm-3', challengeId: 'c-detox-7', userId: 'u-priya', text: 'Third time running this one. Day 2 itch is real, day 5 quiet is worth it.', createdAt: daysAgoIso(6) },
  { id: 'cm-4', challengeId: 'c-fitness-21', userId: 'u-diego', text: 'Scaled sessions to 30 min and still cooked. Great programming, Marcus.', createdAt: daysAgoIso(3) },
  { id: 'cm-5', challengeId: 'c-reading-30', userId: 'u-tomas', text: '20 pages before breakfast changed my mornings completely.', createdAt: daysAgoIso(1) },
];

/** Pre-existing participations + check-ins for personas (streaks are real). */
export function seedParticipation(): { participants: Participation[]; checkins: Checkin[] } {
  const participants: Participation[] = [
    { challengeId: 'c-coding-30', userId: 'u-lina', status: 'active', joinedAt: daysAgoIso(12), currentStreak: 6, longestStreak: 9, completedDays: 10, lastCheckinDate: isoDay(0), completedAt: null },
    { challengeId: 'c-detox-7', userId: 'u-marcus', status: 'completed', joinedAt: daysAgoIso(9), currentStreak: 0, longestStreak: 7, completedDays: 7, lastCheckinDate: isoDay(2), completedAt: daysAgoIso(2) },
    { challengeId: 'c-fitness-21', userId: 'u-aya', status: 'active', joinedAt: daysAgoIso(8), currentStreak: 4, longestStreak: 5, completedDays: 6, lastCheckinDate: isoDay(1), completedAt: null },
  ];
  const checkins: Checkin[] = [];
  let n = 0;
  for (let i = 0; i < 6; i++) {
    checkins.push({ id: `ck-seed-${n++}`, challengeId: 'c-coding-30', userId: 'u-lina', dayNumber: i + 1, date: isoDay(5 - i), note: i === 0 ? 'Opened the repo, fixed a stale test.' : '', createdAt: daysAgoIso(5 - i) });
  }
  for (let i = 0; i < 4; i++) {
    checkins.push({ id: `ck-seed-${n++}`, challengeId: 'c-fitness-21', userId: 'u-aya', dayNumber: i + 1, date: isoDay(4 - i), note: '', createdAt: daysAgoIso(4 - i) });
  }
  return { participants, checkins };
}

export function isoDay(offsetFromToday: number): string {
  const d = new Date(Date.now() + offsetFromToday * 86400_000);
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`;
}
